apiVersion: v1
kind: Service
metadata:
  name: cli
  namespace: ${config['hyperledger.namespace']}
  labels:
    app: hyperledger-fabric
    role: cli
spec:
  type: NodePort
  ports:
    - name: "ssh"
      port: 22
      targetPort: 22
    - name: "peer-grpc"
      port: 7051
      targetPort: 7051
    - name: "peer-cli"
      port: 7052
      targetPort: 7052
  selector:
    app: hyperledger-fabric
    role: cli
