apiVersion: v1
kind: Service
metadata:
  name: membersrvc
  namespace: ${config['hyperledger.namespace']}
  labels:
    app: hyperledger-fabric
    role: membersrvc
spec:
  type: NodePort
  ports:
    - name: "ecap"
      port: 7054
      targetPort: 7054
  selector:
    app: hyperledger-fabric
    role: membersrvc
