apiVersion: v1
kind: Service
metadata:
  name: hyperledger-cli-service
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: cli-node
spec:
  ports:
    - name: "peer-grpc"
      port: 7051
      targetPort: 7051
    - name: "peer-cli"
      port: 7052
      targetPort: 7052
  selector:
    app: hyperledger-fabric
    role: cli-node
