apiVersion: v1
kind: Namespace
metadata:
  name: "hyperledger-fabric"
  labels:
    name: "hyperledger-fabric"
---
apiVersion: v1
kind: Service
metadata:
  name: hyperledger-membersrvc-service
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: membersrvc
spec:
  ports:
  - name: "ecap"
    port: 7054
    targetPort: 7054
  selector:
    app: hyperledger-fabric
    role: membersrvc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperledger-membersrvc-deployment
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: membersrvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger-fabric
      role: membersrvc
  template:
    metadata:
      labels:
        app: hyperledger-fabric
        role: membersrvc
    spec:
      restartPolicy: Always
      containers:
        - name: hyperledger-membersrvc
          image: hyperledger/fabric-membersrvc:latest
          env:
          - name: CORE_LOGGING_LEVEL
            value: "info"
          command: ["membersrvc"]
          ports:
            - containerPort: 7054
---
apiVersion: v1
kind: Service
metadata:
  name: hyperledger-cli-service
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: cli
spec:
  ports:
  - name: "peer-grpc"
    port: 7051
    targetPort: 7051
  - name: "peer-cli"
    port: 7052
    targetPort: 7052
  selector:
    app: hyperledger-fabric
    role: cli
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperledger-cli-deployment
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger-fabric
      role: cli
  template:
    metadata:
      labels:
        app: hyperledger-fabric
        role: cli
    spec:
      restartPolicy: Always
      containers:
        - name: hyperledger-cli
          image: hyperledger/fabric-peer:latest
          env:
          - name: CORE_VM_ENDPOINT
            value: "TODO"
          - name: CORE_PEER_ADDRESS
            value: "TODO"
          - name: CORE_PEER_ADDRESSAUTODETECT
            value: "false"
          - name: CORE_SECURITY_ENABLED
            value: "true"
          - name: CORE_SECURITY_PRIVACY
            value: "true"
          - name: HYPERLEDGER_ROOT_NODE_ADDRESS
            value: "TODO"
          - name: HYPERLEDGER_MEMBERSRVC_NODE_ADDRESS
            value: "TODO"
          - name: APP_HOME
            value: "/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go/asset_management/app"
          command: ["TODO"]
          ports:
            - containerPort: 7051
            - containerPort: 7052
---
apiVersion: v1
kind: Service
metadata:
  name: hyperledger-sequence-node-service
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: sequence-node
spec:
  ports:
  - name: "http"
    port: 9999
    targetPort: 9999
  selector:
    app: hyperledger-fabric
    role: sequence-node
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperledger-sequence-node-deployment
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: sequence-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger-fabric
      role: sequence-node
  template:
    metadata:
      labels:
        app: hyperledger-fabric
        role: sequence-node
    spec:
      restartPolicy: Always
      containers:
        - name: hyperledger-sequence-node
          image: cloudsoft/hyperledger-sequence-node:latest
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: hyperledger-secret-keys-node-service
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: secret-keys-node
spec:
  ports:
  - name: "http"
    port: 9999
    targetPort: 9999
  selector:
    app: hyperledger-fabric
    role: secret-keys-node
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperledger-secret-keys-node-deployment
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: secret-keys-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger-fabric
      role: secret-keys-node
  template:
    metadata:
      labels:
        app: hyperledger-fabric
        role: secret-keys-node
    spec:
      restartPolicy: Always
      containers:
        - name: hyperledger-secret-keys-node
          image: cloudsoft/hyperledger-secret-keys-node:latest
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: hyperledger-validating-peer-root-service
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: validating-peer-root
spec:
  ports:
  - name: "rest"
    port: 7050
    targetPort: 7050
  - name: "peer-grpc"
    port: 7051
    targetPort: 7051
  - name: "peer-cli"
    port: 7052
    targetPort: 7052
  - name: "peer-events"
    port: 7053
    targetPort: 7053
  selector:
    app: hyperledger-fabric
    role: validating-peer-root
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperledger-validating-peer-root-deployment
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: validating-peer-root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger-fabric
      role: validating-peer-root
  template:
    metadata:
      labels:
        app: hyperledger-fabric
        role: validating-peer-root
    spec:
      restartPolicy: Always
      containers:
        - name: hyperledger-validating-peer-root
          image: hyperledger/fabric-peer:latest
          env:
          - name: CORE_VM_ENDPOINT
            value: "TODO"
          - name: CORE_PEER_ID
            value: "TODO"
          - name: CORE_PEER_ADDRESS
            value: "TODO"
          - name: CORE_PEER_ADDRESSAUTODETECT
            value: "false"
          - name: CORE_PEER_NETWORKID
            value: "dev"
          - name: CORE_LOGGING_LEVEL
            value: "info"
          - name: CORE_SECURITY_ENABLED
            value: "true"
          - name: CORE_SECURITY_PRIVACY
            value: "true"
          - name: CORE_SECURITY_ENROLLID
            value: "TODO"
          - name: CORE_SECURITY_ENROLLSECRET
            value: "TODO"
          - name: CORE_PEER_PKI_ECA_PADDR
            value: "TODO"
          - name: CORE_PEER_PKI_TCA_PADDR
            value: "TODO"
          - name: CORE_PEER_PKI_TLSCA_PADDR
            value: "TODO"
          - name: CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN
            value: "pbft"
          - name: CORE_PBFT_GENERAL_MODE
            value: "batch"
          - name: CORE_PBFT_GENERAL_N
            value: "TODO"
          - name: CORE_PBFT_GENERAL_TIMEOUT_REQUEST
            value: "120s"
          command: ["peer node start"]
          ports:
            - containerPort: 7050
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
---
apiVersion: v1
kind: Service
metadata:
  name: hyperledger-validating-peer-node-service
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: validating-peer-node
spec:
  ports:
  - name: "rest"
    port: 7050
    targetPort: 7050
  - name: "peer-grpc"
    port: 7051
    targetPort: 7051
  - name: "peer-cli"
    port: 7052
    targetPort: 7052
  - name: "peer-events"
    port: 7053
    targetPort: 7053
  selector:
    app: hyperledger-fabric
    role: validating-peer-node
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperledger-validating-peer-node-deployment
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: validating-peer-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hyperledger-fabric
      role: validating-peer-node
  template:
    metadata:
      labels:
        app: hyperledger-fabric
        role: validating-peer-node
    spec:
      restartPolicy: Always
      containers:
        - name: hyperledger-validating-peer-node
          image: hyperledger/fabric-peer:latest
          env:
          - name: CORE_VM_ENDPOINT
            value: "TODO"
          - name: CORE_PEER_ID
            value: "TODO"
          - name: CORE_PEER_ADDRESS
            value: "TODO"
          - name: CORE_PEER_ADDRESSAUTODETECT
            value: "false"
          - name: CORE_PEER_NETWORKID
            value: "dev"
          - name: CORE_LOGGING_LEVEL
            value: "info"
          - name: CORE_SECURITY_ENABLED
            value: "true"
          - name: CORE_SECURITY_PRIVACY
            value: "true"
          - name: CORE_SECURITY_ENROLLID
            value: "TODO"
          - name: CORE_SECURITY_ENROLLSECRET
            value: "TODO"
          - name: CORE_PEER_PKI_ECA_PADDR
            value: "TODO"
          - name: CORE_PEER_PKI_TCA_PADDR
            value: "TODO"
          - name: CORE_PEER_PKI_TLSCA_PADDR
            value: "TODO"
          - name: CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN
            value: "pbft"
          - name: CORE_PBFT_GENERAL_MODE
            value: "batch"
          - name: CORE_PBFT_GENERAL_N
            value: "TODO"
          - name: CORE_PBFT_GENERAL_TIMEOUT_REQUEST
            value: "120s"
          - name: CORE_PEER_DISCOVERY_ROOTNODE
            value: "TODO"
          command: ["peer node start"]
          ports:
            - containerPort: 7050
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053