apiVersion: v1
kind: Service
metadata:
  name: membersrvc
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-fabric
    role: membersrvc
spec:
  ports:
    - name: "ecap"
      port: 7054
      targetPort: 7054
  selector:
    app: hyperledger-fabric
    role: membersrvc
